# Generated by Django 5.1.7 on 2025-03-13 12:27

import apps.images.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='título')),
                ('original_image', models.ImageField(upload_to=apps.images.models.image_upload_path, verbose_name='imagen original')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de subida')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='clave de sesión')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imágenes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/thumbnails/', verbose_name='archivo')),
                ('width', models.PositiveIntegerField(verbose_name='ancho')),
                ('height', models.PositiveIntegerField(verbose_name='alto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='images.image', verbose_name='imagen original')),
            ],
            options={
                'verbose_name': 'miniatura',
                'verbose_name_plural': 'miniaturas',
                'ordering': ['width', 'height'],
            },
        ),
    ]
